# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-18 17:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import liqorice.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.CharField(default=liqorice.models.generateUUID, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('author', models.CharField(max_length=200)),
                ('post_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('content', models.TextField()),
            ],
        ),
    ]
